version: '3.0'
services:
  angular:
    build: app
    ports:
    - "4200:4200"
    links:
    - express

  express:
    build: server
    ports:
    - "3000:3000"
    links:
    - mongodb

  mongodb:
    image: mongo
    ports:
    - "27017:27017"

  mongo-seed:
    build: mongo-seed
    links:
    - mongodb
